### ISSUE TITLE
スポンサーを掲載する

### ISSUE THREAD

**Issue by smellman** [osmfj/sotmjp2020#8]
- [ ] ソフトウェアファクトリーさん
- [ ] Georepublic さん
- [ ] MIERUNE さん

**Comment by nyampire** [comment]
ソフトウェアファクトリーさんとGeorepublicさんについては、OSMFJのウェブサイトに掲載しているものを利用可能です。

https://github.com/osmfj/osmfj-website/tree/gh-pages/img/logos
